### ISSUE TITLE
wizchip_connect()中while循环时间太长，会造成看门狗没法喂，使得系统重启

### ISSUE THREAD

**Issue by shishirong** [RT-Thread-packages/wiznet#45]
wizchip_socket.c
int8_t wizchip_connect(uint8_t sn, uint8_t * addr, uint16_t port)之中
```c
while (getSn_SR(sn) != SOCK_ESTABLISHED) 
{
    if (getSn_IR(sn) & Sn_IR_TIMEOUT) 
    {
        setSn_IR(sn, Sn_IR_TIMEOUT);
        return SOCKERR_TIMEOUT;
    }

    if (getSn_SR(sn) == SOCK_CLOSED) 
    {
        return SOCKERR_SOCKCLOSED;
    }
}
```

**Comment by xiangxistu** [comment]
在开启线程守护进程时，会导致系统频繁重启的问题，对吧

**Comment by RulerCN** [comment]
Many places in this project have the similar bugs. I don't think it's a normal design solution. But if you don't abandon it, how else can you do besides adding rt_thread_mdelay(1)?
