### ISSUE TITLE
wiz_recvfrom()错误时返回值不能区分错误的详细类型

### ISSUE THREAD

**Issue by shishirong** [RT-Thread-packages/wiznet#46]
比如发生“WIZnet recvfrom failed, get socket(%d) register state(%d) error.”和“WIZnet recvfrom input data or length error!”等错误都是返回-1。

**Comment by xiangxistu** [comment]
返回的错误信息，确实都为 -RT_ERROR。有什么好的建议来区分吗？

**Comment by shishirong** [comment]
算了，将就-RT_ERROR吧，也不是不能用
