### ISSUE TITLE
rt_thread最新版本已将sal.h修改为sal_low_lvl.h，这个固件包还会更新么以适配4.1.0

### ISSUE THREAD

**Issue by baiqiudi** [RT-Thread-packages/wiznet#70]
![image](https://user-images.githubusercontent.com/44767926/206068001-d5b0087f-28c7-4083-9f8c-0ff7c5c345df.png)

**Comment by mysterywolf** [comment]
https://github.com/RT-Thread-packages/wiznet/pull/69

**Comment by baiqiudi** [comment]
好的，谢谢回复

Man, Jianting (Meco) ***@***.***> 于2022年12月8日周四 11:20写道：
